%YAML 1.2
---
max_seq_len: !!int &max_len 4096

tokens_of_interest: &tois
  - RESP//imv
  - DSCG//expired
  - LABEL//anemia_init
  - LABEL//crrt_init
  - LABEL//hyperk_init
  - LABEL//hypok_init
  - LABEL//hyperna_init
  - LABEL//hypona_init
  - LABEL//hypertension_init
  - LABEL//hypotension_init
  - LABEL//pressor_init
  - LABEL//tachy_init

score:
  max_len: *max_len
  n_samp: !!int 10 # MC samples per input per trajectory type
  target_tokens: *tois # token-based outcomes of interest
  end_tokens: # tokens that naturally terminate a sequence
    - EOS
  suppressed_tokens: [] # tokens to suppress (e.g. PAD) via logit bias
  trunc_id: !!int 0 # token id to force after time horizon exceeded
  batch_size: !!int 64
